// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic.proto

package restaurant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Name struct {
	En                   string   `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Ja                   string   `protobuf:"bytes,2,opt,name=ja,proto3" json:"ja,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{1}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Name) GetJa() string {
	if m != nil {
		return m.Ja
	}
	return ""
}

type Description struct {
	En                   string   `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Ja                   string   `protobuf:"bytes,2,opt,name=ja,proto3" json:"ja,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Description) Reset()         { *m = Description{} }
func (m *Description) String() string { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()    {}
func (*Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{2}
}

func (m *Description) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Description.Unmarshal(m, b)
}
func (m *Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Description.Marshal(b, m, deterministic)
}
func (m *Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Description.Merge(m, src)
}
func (m *Description) XXX_Size() int {
	return xxx_messageInfo_Description.Size(m)
}
func (m *Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Description proto.InternalMessageInfo

func (m *Description) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Description) GetJa() string {
	if m != nil {
		return m.Ja
	}
	return ""
}

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{3}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RestId struct {
	RestId               string   `protobuf:"bytes,1,opt,name=rest_id,json=restId,proto3" json:"rest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestId) Reset()         { *m = RestId{} }
func (m *RestId) String() string { return proto.CompactTextString(m) }
func (*RestId) ProtoMessage()    {}
func (*RestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{4}
}

func (m *RestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestId.Unmarshal(m, b)
}
func (m *RestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestId.Marshal(b, m, deterministic)
}
func (m *RestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestId.Merge(m, src)
}
func (m *RestId) XXX_Size() int {
	return xxx_messageInfo_RestId.Size(m)
}
func (m *RestId) XXX_DiscardUnknown() {
	xxx_messageInfo_RestId.DiscardUnknown(m)
}

var xxx_messageInfo_RestId proto.InternalMessageInfo

func (m *RestId) GetRestId() string {
	if m != nil {
		return m.RestId
	}
	return ""
}

type RestGroupId struct {
	RestGroupId          string   `protobuf:"bytes,1,opt,name=rest_group_id,json=restGroupId,proto3" json:"rest_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestGroupId) Reset()         { *m = RestGroupId{} }
func (m *RestGroupId) String() string { return proto.CompactTextString(m) }
func (*RestGroupId) ProtoMessage()    {}
func (*RestGroupId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{5}
}

func (m *RestGroupId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestGroupId.Unmarshal(m, b)
}
func (m *RestGroupId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestGroupId.Marshal(b, m, deterministic)
}
func (m *RestGroupId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestGroupId.Merge(m, src)
}
func (m *RestGroupId) XXX_Size() int {
	return xxx_messageInfo_RestGroupId.Size(m)
}
func (m *RestGroupId) XXX_DiscardUnknown() {
	xxx_messageInfo_RestGroupId.DiscardUnknown(m)
}

var xxx_messageInfo_RestGroupId proto.InternalMessageInfo

func (m *RestGroupId) GetRestGroupId() string {
	if m != nil {
		return m.RestGroupId
	}
	return ""
}

type TaxId struct {
	TaxId                string   `protobuf:"bytes,1,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaxId) Reset()         { *m = TaxId{} }
func (m *TaxId) String() string { return proto.CompactTextString(m) }
func (*TaxId) ProtoMessage()    {}
func (*TaxId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{6}
}

func (m *TaxId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaxId.Unmarshal(m, b)
}
func (m *TaxId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaxId.Marshal(b, m, deterministic)
}
func (m *TaxId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxId.Merge(m, src)
}
func (m *TaxId) XXX_Size() int {
	return xxx_messageInfo_TaxId.Size(m)
}
func (m *TaxId) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxId.DiscardUnknown(m)
}

var xxx_messageInfo_TaxId proto.InternalMessageInfo

func (m *TaxId) GetTaxId() string {
	if m != nil {
		return m.TaxId
	}
	return ""
}

type CurrencyId struct {
	CurrencyId           string   `protobuf:"bytes,1,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyId) Reset()         { *m = CurrencyId{} }
func (m *CurrencyId) String() string { return proto.CompactTextString(m) }
func (*CurrencyId) ProtoMessage()    {}
func (*CurrencyId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cc45f6ac745dd88, []int{7}
}

func (m *CurrencyId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyId.Unmarshal(m, b)
}
func (m *CurrencyId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyId.Marshal(b, m, deterministic)
}
func (m *CurrencyId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyId.Merge(m, src)
}
func (m *CurrencyId) XXX_Size() int {
	return xxx_messageInfo_CurrencyId.Size(m)
}
func (m *CurrencyId) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyId.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyId proto.InternalMessageInfo

func (m *CurrencyId) GetCurrencyId() string {
	if m != nil {
		return m.CurrencyId
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "restaurant.Empty")
	proto.RegisterType((*Name)(nil), "restaurant.Name")
	proto.RegisterType((*Description)(nil), "restaurant.Description")
	proto.RegisterType((*Id)(nil), "restaurant.Id")
	proto.RegisterType((*RestId)(nil), "restaurant.RestId")
	proto.RegisterType((*RestGroupId)(nil), "restaurant.RestGroupId")
	proto.RegisterType((*TaxId)(nil), "restaurant.TaxId")
	proto.RegisterType((*CurrencyId)(nil), "restaurant.CurrencyId")
}

func init() {
	proto.RegisterFile("basic.proto", fileDescriptor_0cc45f6ac745dd88)
}

var fileDescriptor_0cc45f6ac745dd88 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0xc6, 0x71, 0xba, 0xb8, 0x5b, 0x7c, 0x82, 0x1e, 0x82, 0x62, 0x4f, 0xbe, 0xcc, 0x41, 0xbc,
	0x54, 0x10, 0x3f, 0x82, 0x8a, 0xe4, 0xe2, 0xa1, 0x78, 0x97, 0x69, 0x12, 0x24, 0x85, 0x66, 0x97,
	0xd9, 0x59, 0x68, 0xbf, 0xbd, 0x64, 0xd5, 0xee, 0xb1, 0xc7, 0xff, 0x3c, 0xbf, 0x43, 0x08, 0xcc,
	0x9a, 0xfb, 0xe4, 0x1f, 0x3b, 0x69, 0xb5, 0xb5, 0x90, 0xd8, 0x2b, 0x0f, 0xc2, 0x59, 0x69, 0x8e,
	0xfa, 0x6d, 0xdb, 0xe9, 0x9e, 0xee, 0x71, 0xf2, 0xc1, 0xdb, 0x68, 0xcf, 0x51, 0xc5, 0xbc, 0x98,
	0xdd, 0xce, 0x1e, 0x4e, 0x57, 0x55, 0xcc, 0xa5, 0x37, 0xbc, 0xa8, 0x7e, 0x7b, 0xc3, 0xb4, 0x84,
	0x79, 0x8d, 0xbd, 0x97, 0xd4, 0x69, 0x6a, 0xf3, 0x51, 0x7e, 0x81, 0xca, 0x85, 0x72, 0x4d, 0xe1,
	0x5f, 0xa5, 0x40, 0x77, 0x68, 0x56, 0xb1, 0x57, 0x17, 0xec, 0x15, 0xe6, 0xe5, 0x35, 0x5f, 0x87,
	0xb9, 0x91, 0x71, 0xa0, 0x27, 0x98, 0x42, 0xde, 0xa5, 0x1d, 0x3a, 0x17, 0x2c, 0xe1, 0x6c, 0x74,
	0xdf, 0xa5, 0x27, 0x6d, 0x64, 0x32, 0x74, 0x8d, 0xfa, 0x93, 0x77, 0x2e, 0xd8, 0x4b, 0x34, 0xca,
	0xbb, 0x49, 0xd5, 0x5a, 0xce, 0xb4, 0x04, 0x5e, 0x06, 0x91, 0x98, 0xfd, 0xde, 0x05, 0x7b, 0x03,
	0xe3, 0xff, 0x6a, 0x92, 0xf0, 0x07, 0xb0, 0x6e, 0xc6, 0xdf, 0x7a, 0xfe, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x69, 0x02, 0xa0, 0x3c, 0x01, 0x00, 0x00,
}
