// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: restaurant_group.proto

package restaurant

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _restaurant_group_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on RestaurantGroup with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RestaurantGroup) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for Hasword

	// no validation rules for HashwordSalt

	for idx, item := range m.GetContacts() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RestaurantGroupValidationError{
					field:  fmt.Sprintf("Contacts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for PersonOfContact

	for idx, item := range m.GetRestaurants() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RestaurantGroupValidationError{
					field:  fmt.Sprintf("Restaurants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RestaurantGroupValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RestaurantGroupValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// RestaurantGroupValidationError is the validation error returned by
// RestaurantGroup.Validate if the designated constraints aren't met.
type RestaurantGroupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RestaurantGroupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RestaurantGroupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RestaurantGroupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RestaurantGroupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RestaurantGroupValidationError) ErrorName() string { return "RestaurantGroupValidationError" }

// Error satisfies the builtin error interface
func (e RestaurantGroupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRestaurantGroup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RestaurantGroupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RestaurantGroupValidationError{}

// Validate checks the field values on RestaurantGroup_Contact with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RestaurantGroup_Contact) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PhoneNumber

	// no validation rules for Email

	// no validation rules for Name

	return nil
}

// RestaurantGroup_ContactValidationError is the validation error returned by
// RestaurantGroup_Contact.Validate if the designated constraints aren't met.
type RestaurantGroup_ContactValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RestaurantGroup_ContactValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RestaurantGroup_ContactValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RestaurantGroup_ContactValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RestaurantGroup_ContactValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RestaurantGroup_ContactValidationError) ErrorName() string {
	return "RestaurantGroup_ContactValidationError"
}

// Error satisfies the builtin error interface
func (e RestaurantGroup_ContactValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRestaurantGroup_Contact.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RestaurantGroup_ContactValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RestaurantGroup_ContactValidationError{}
